### ISSUE TITLE
Missing step from setup instructions

### ISSUE THREAD

**Issue by adam-binks** [TweetyProjectTeam/TweetyProject#6]
Hey! I was setting up Tweety using Maven on the command line as per [these instructions](http://tweetyproject.org/doc/install-commandline.html). To get `mvn package` to work without errors, I needed to add the following lines to `pom.xml`:

```
<properties>
   <maven.compiler.source>1.8</maven.compiler.source>
   <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```

I'm not sure if targeting 1.8 is the correct value. Could be useful to add this to the instructions for other people getting started.

**Comment by sfranke43** [comment]
Hi! Thank you for your comment. I'll look into the issue

**Comment by sfranke43** [comment]
I added the missing lines you suggested to the pom. Thanks again for letting us know about this
